document.addEventListener('DOMContentLoaded', async function() {

    // ============================================================
    // 1. CONFIGURATION (Edit these!)
    // ============================================================
    
    const CONFIG = {
        // Your GitHub username
        username: 'tanaderizcky',
        
        // Personal Access Token (optional but recommended)
        // Get from: GitHub Settings → Developer Settings → Personal Access Tokens
        token: '',  // Leave empty if you don't have one yet
        
        // How many repos to show (latest 3)
        maxProjects: 3,
        
        // Topics to include (repos MUST have at least one of these)
        includeTopics: [], // ← Empty array means: include ALL repos!
        
        // Repos to hide (by name)
        hideRepos: [
            'tanaderizcky.github.io',  // Your portfolio repo
            //'test-repo', 
            //'learning',
            //'temp'
        ],
        
        // ============================================================
        // NO DEMO PROJECTS - Show nothing if no repos
        // ============================================================
    };

    // ============================================================
    // 2. DOM ELEMENTS
    // ============================================================
    
    const container = document.getElementById('projects-container');

    // ============================================================
    // 3. HELPER FUNCTIONS
    // ============================================================
    
    async function githubFetch(url) {
        const options = { headers: {} };
        if (CONFIG.token) {
            options.headers['Authorization'] = `token ${CONFIG.token}`;
        }
        const response = await fetch(url, options);
        if (!response.ok) {
            throw new Error(`GitHub API error: ${response.status}`);
        }
        return await response.json();
    }

    // Create a project card
    function createProjectCard(project) {
        const card = document.createElement('div');
        card.className = 'project-card';
        
        // GitHub OpenGraph image or placeholder
        const imageUrl = `https://opengraph.githubassets.com/1/${CONFIG.username}/${project.name}`;
        //it's auto generated by github, so it will always exist, but we can add error handling just in case
        
        // Get tags
        const tags = project.topics || [project.language || 'Code'];
        
        // Get description
        let description = project.description || 'No description provided';
        if (description.length > 200) {
            description = description.substring(0, 200) + '...';
        }
        card.innerHTML = `
        <div class="project-image">
            <img src="${imageUrl}" alt="${project.name}" loading="lazy" 
                 onerror="this.parentElement.innerHTML = '<div class=\\'project-placeholder\\' style=\\'background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\\'><span>📁</span></div>'">
        </div>
        <div class="project-info">
            <h3>${project.name.replace(/-/g, ' ')}</h3>
            <p>${description}</p>
            <div class="project-tags">
                ${tags.slice(0, 3).map(tag => `<span>${tag}</span>`).join('')}
                ${project.stargazers_count ? `<span>⭐ ${project.stargazers_count}</span>` : ''}
                ${project.forks_count ? `<span>🔄 ${project.forks_count}</span>` : ''}
            </div>
            ${project.name === 'yun-yueduqi' ? ` 
                <div div class="button-group">
                    <a href="https://tanaderizcky.github.io/yun-yueduqi/index.html" target="_blank" class="btn btn-small">
                        🌐 View Result
                    </a> 
                    <a href="${project.html_url}" target="_blank" class="btn btn-small" style="background: #6c757d;">
                        📂 View Code
                    </a>
                </div>
            ` : `
                <a href="${project.html_url}" target="_blank" class="btn btn-small">
                    📂 View Code
                </a> 
            `}
            </div> 
        `;
        
        return card;
    }

    // Show empty state (no projects yet)
    function showEmptyState() {
        container.innerHTML = `
            <div class="empty-state">
                <div class="empty-state-content">
                    <span class="emoji">🚀</span>
                    <h3>No Projects Yet</h3>
                    <p>I'm currently building my first projects.</p>
                    <p class="sub-message">Check back soon to see what I've been working on!</p>
                </div>
            </div>
        `;
    }

    // ============================================================
    // 4. MAIN LOGIC
    // ============================================================
    
    try {
        // Clear loading message
        container.innerHTML = '';
        
        // Fetch repositories from GitHub
        const repos = await githubFetch(
            `https://api.github.com/users/${CONFIG.username}/repos?sort=pushed&direction=desc&per_page=10`
        );
        
        // Filter repos
        let filteredRepos = repos.filter(repo => {
            // Skip archived repos
            if (repo.archived) return false;
            
            // Skip forks
            if (repo.fork) return false;
            
            // Skip hidden repos
            if (CONFIG.hideRepos.includes(repo.name)) return false;
            
            // Check topics (if includeTopics is set)
            if (CONFIG.includeTopics.length > 0) {
                const hasTopic = repo.topics && 
                    repo.topics.some(t => CONFIG.includeTopics.includes(t));
                if (!hasTopic) return false;
            }
            
            return true;
        });
        
        // Take only the latest 3
        filteredRepos = filteredRepos.slice(0, CONFIG.maxProjects);
        
        // ============================================================
        // 5. DISPLAY RESULTS
        // ============================================================
        
        if (filteredRepos.length === 0) {
            // NO PROJECTS - Show empty state
            showEmptyState();
        } else {
            // SHOW PROJECTS
            filteredRepos.forEach(repo => {
                const card = createProjectCard(repo);
                container.appendChild(card);
            });
        }
        
    } catch (error) {
        // ERROR - Show empty state as fallback
        console.error('Error fetching projects:', error);
        showEmptyState();
    }
});
